### PR TITLE
Add dynamic memory rule

### PR DESCRIPTION
**Pull request by Hazeti**
Add rule about how holding onto dynamic can be dangerous

### CODE REVIEW

**Comment by Hazeti** [comment]
Would like to get some feedback regarding this PR. Does the structure / comments make sense? Does it get the message across? Is the example too arbitrary?

**Comment by valentingalea** [comment]
I like it! I bet this is from actual production bugs
I think it gets the point across well

what's happening with the other (unrelated) commits? or the last merge solves that?

**Comment by Hazeti** [comment]
I'm still getting used to Git. I have no idea why they are there; they've already been pulled afaik and I don't know how to get rid of them!

**Comment by valentingalea** [comment]
I wonder tho if it can be rewritten to be .cpp side only? the .h should be "architectural" as much as possible

**Comment by Hazeti** [comment]
I did wonder that also. It would be possible but a bit weird. You'd have to
pass the array through to innocentcall. It would work, would it get the
message across? I also wasn't a fan of adding things to the .h file.

I'll make the change and see how it feels.

**Comment by Hazeti** [comment]
Updated.

I honestly don't know what's going on with whitespaces and this file and why it's always changing. had the old "Inconsistent Line Endings" dialogue box appear and changed them all to Windows (CR LF).

**Comment by valentingalea** [comment]
Yeah the move the .cpp is way better

With that said I think it's best to just re-create this PR :) the diff of the .cpp is massive i'ts pretty much a new file I don't know what you did :P

**Comment by valentingalea** [comment]
I think I know what happened - you created this PR from your old branch you used to do the others? you should restart with a "clean" master with latest then branch and PR

**Comment by Hazeti** [comment]
Trying a clean PR

**Pull request closed without merging**
