### PR TITLE
Remove incorrect point on not initialising TWeakObjPtr

### PR DESCRIPTION
**Pull request by Hazeti**
The standard stated not to initialise TWeakObjPtr as that could cause compile errors, this is incorrect.

Also made the standard more compliant with the column guide.

### CODE REVIEW

**Review by valentingalea — CHANGES_REQUESTED** [review]
All the tabs got converted in spaces! Was this by accident?

**Comment by Hazeti** [comment]
That's how my VS is setup so it happens automatically.
Is this about to go into a tabs vs spaces debate? :D

**Comment by valentingalea** [comment]
yes it will :-P

we always use tabs for indentation - that's Epic's standard as well

**Comment by Hazeti** [comment]
Alright, you got me with the epic standard. Should have fixed it all up now.

**Review by valentingalea — APPROVED** [review]

**Pull request merged**
